Add start projct template.
andrjak/ITiROD pull request #1
Opened 2020-05-11 16:11 UTC by andrjak

2020-05-12 12:07 UTC, gmltA requested changes
Неяк мала.
Дадайце, калі ласка, тэгі на старонку з плейлістамі. І пакажыце, як будуць, напрыклад, формы рэгістрацыі / аўтарзыацыі выглядаць.

2020-05-12 14:49 UTC, andrjak commented
Добавил страницы регистрации и авторизации. Немного изменил страницу с плейлистами, добавил на неё теги.

2020-05-14 11:43 UTC, gmltA requested changes
Ну а на новыя старонкі тэгі чаму вы не дадалі?

На старонке з плейлістамі разметка кнопак няверная.

2020-05-14 21:25 UTC, andrjak commented
Добавил Html для Login и Registration, изменил разметку для кнопок в Playlists.

2020-05-15 13:39 UTC, gmltA requested changes
**Login With Html**

У адной з кнопак няверны тэг.

2020-05-15 20:06 UTC, andrjak commented
Изменил кнопку на ссылку.

2020-05-18 14:02 UTC, gmltA approved these changes

2020-05-19 15:42 UTC, merged